In [2]:
import torch


def test_meshgrid():
    idx_1 = torch.arange(4)
    idx_2 = torch.arange(3) + 5
    idx_x, idx_y = torch.meshgrid(idx_1, idx_2, indexing="ij")
    stacked = torch.stack([idx_x.flatten(), idx_y.flatten()], dim=1)
    print(idx_x)
    print(idx_y)
    print(stacked)

    # standard way
    idx_x, idx_y = torch.meshgrid(idx_1, idx_2, indexing="xy")
    stacked = torch.stack([idx_x.flatten(), idx_y.flatten()], dim=1)
    print(idx_x)
    print(idx_y)
    print(stacked)


test_meshgrid()


tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])
tensor([[5, 6, 7],
        [5, 6, 7],
        [5, 6, 7],
        [5, 6, 7]])
tensor([[0, 5],
        [0, 6],
        [0, 7],
        [1, 5],
        [1, 6],
        [1, 7],
        [2, 5],
        [2, 6],
        [2, 7],
        [3, 5],
        [3, 6],
        [3, 7]])
tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])
tensor([[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])
tensor([[0, 5],
        [1, 5],
        [2, 5],
        [3, 5],
        [0, 6],
        [1, 6],
        [2, 6],
        [3, 6],
        [0, 7],
        [1, 7],
        [2, 7],
        [3, 7]])


In [6]:
def test_unbind():
    x = torch.tensor([[1, 2], [1, 2], [1, 2]])
    x0, x1 = x.unbind(dim=1)
    print(x0)
    print(x1)
    stacked = torch.stack([x0, x1], dim=1)
    print(stacked)


test_unbind()


tensor([1, 1, 1])
tensor([2, 2, 2])
tensor([[1, 2],
        [1, 2],
        [1, 2]])
